### ISSUE TITLE
Closes immediately after opening via QUsb2Snes

### ISSUE THREAD

**Issue by melink14** [Skarsnik/Button-Mash#2]
It opens for ~5 seconds and then closes immediately. The window can't be interacted with.

I'm using a Nintendo Spy box. (Though given it's QUsb2Snes that shouldn't matter)

**Comment by Skarsnik** [comment]
Did you try the last Button Mash release?

**Comment by melink14** [comment]
Good question. I was using the version that came with QUsb2Snes so wasn't sure. I downloaded beta 4.7 and tried again with the same result.

Opening from QUsb2Snes menu or opening the exe directly both lead to the same result. Grabbed a screencap before it disappeared:
![Desktop Screenshot 2021 11 06 - 10 59 56 49](https://user-images.githubusercontent.com/1176550/140594133-3a2c9638-391d-479d-919b-88ae2ad65580.png)

In the QUsb2Snes logs it just mentiones that it opened the exe with no other logs.

Let me know if there's more I can get directly from button mash!

**Comment by Skarsnik** [comment]
Last release of Button Mash is beta11 x)
You don't need to start it from QUsb2Snes btw, especially if you use an arduino based solution.

**Comment by melink14** [comment]
Ah, thanks, I see beta11 tagged but not compiled as a release. 

I don't mind compiling if there's a simple tool chain to do it though!

**Comment by Skarsnik** [comment]
Ah, I forgot to publish the release

**Comment by melink14** [comment]
Great; Version 11 works fine now! Nice work on the backwards compatibility! (Now I just need to debug my arduino device since it's not actually showing up; works great via usb2snes  htough)
